"""add_api_partner_webhooks

Revision ID: 087e49fa2428
Revises: l6f7g8h9i0j1
Create Date: 2026-02-27 23:16:51.337726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '087e49fa2428'
down_revision: Union[str, None] = 'l6f7g8h9i0j1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_partner_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_partner_webhooks_is_active'), 'api_partner_webhooks', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_partner_webhooks_user_id'), 'api_partner_webhooks', ['user_id'], unique=False)
    op.create_table('webhook_delivery_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_id'], ['api_partner_webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_logs_signal_id'), 'webhook_delivery_logs', ['signal_id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_logs_webhook_id'), 'webhook_delivery_logs', ['webhook_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.drop_index('ix_api_partner_entitlements_access_plan', table_name='api_partner_entitlements')
    op.drop_constraint('uq_api_partner_entitlements_user_id', 'api_partner_entitlements', type_='unique')
    op.drop_index('ix_api_partner_keys_user_active', table_name='api_partner_keys')
    op.drop_index('ix_api_partner_usage_periods_user_period', table_name='api_partner_usage_periods')
    op.drop_index('ix_cross_market_divergence_events_idempotency_key', table_name='cross_market_divergence_events')
    op.create_index(op.f('ix_cross_market_divergence_events_idempotency_key'), 'cross_market_divergence_events', ['idempotency_key'], unique=True)
    op.drop_index('ix_signals_created_at_desc_time_bucket', table_name='signals')
    op.drop_index('ix_signals_time_bucket', table_name='signals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_signals_time_bucket', 'signals', ['time_bucket'], unique=False)
    op.create_index('ix_signals_created_at_desc_time_bucket', 'signals', [sa.text('created_at DESC'), 'time_bucket'], unique=False)
    op.drop_index(op.f('ix_cross_market_divergence_events_idempotency_key'), table_name='cross_market_divergence_events')
    op.create_index('ix_cross_market_divergence_events_idempotency_key', 'cross_market_divergence_events', ['idempotency_key'], unique=False)
    op.create_index('ix_api_partner_usage_periods_user_period', 'api_partner_usage_periods', ['user_id', 'period_start'], unique=False)
    op.create_index('ix_api_partner_keys_user_active', 'api_partner_keys', ['user_id', 'is_active'], unique=False)
    op.create_unique_constraint('uq_api_partner_entitlements_user_id', 'api_partner_entitlements', ['user_id'])
    op.create_index('ix_api_partner_entitlements_access_plan', 'api_partner_entitlements', ['api_access_enabled', 'plan_code'], unique=False)
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_webhook_delivery_logs_webhook_id'), table_name='webhook_delivery_logs')
    op.drop_index(op.f('ix_webhook_delivery_logs_signal_id'), table_name='webhook_delivery_logs')
    op.drop_table('webhook_delivery_logs')
    op.drop_index(op.f('ix_api_partner_webhooks_user_id'), table_name='api_partner_webhooks')
    op.drop_index(op.f('ix_api_partner_webhooks_is_active'), table_name='api_partner_webhooks')
    op.drop_table('api_partner_webhooks')
    # ### end Alembic commands ###
