"""Add Kalshi gate metadata columns to Signal

Revision ID: 54ec1419cd2d
Revises: 087e49fa2428
Create Date: 2026-02-28 02:24:21.910912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ec1419cd2d'
down_revision: Union[str, None] = '087e49fa2428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('kalshi_liquidity_skew', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('kalshi_skew_bucket', sa.String(length=16), nullable=True))
    op.add_column('signals', sa.Column('kalshi_gate_pass', sa.Boolean(), nullable=True))
    op.add_column('signals', sa.Column('kalshi_gate_threshold', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('kalshi_gate_mode', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'kalshi_gate_mode')
    op.drop_column('signals', 'kalshi_gate_threshold')
    op.drop_column('signals', 'kalshi_gate_pass')
    op.drop_column('signals', 'kalshi_skew_bucket')
    op.drop_column('signals', 'kalshi_liquidity_skew')
    # ### end Alembic commands ###
