"""Add discord_id to users and make password_hash nullable

Revision ID: c85f77f1ec93
Revises: 0001_initial
Create Date: 2026-02-21 06:36:12.726180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85f77f1ec93'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_games_event_id', 'games', type_='unique')
    op.add_column('users', sa.Column('discord_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'discord_id')
    op.create_unique_constraint('uq_games_event_id', 'games', ['event_id'])
    # ### end Alembic commands ###
